[project]
name = "kirin-rewrite-tracer-docs-fusion"
version = "0"
requires-python = ">=3.13,<3.14"
dependencies = [
  "bloqade-lanes==0.11.1",
  "kirin-toolchain @ git+https://github.com/QuEraComputing/kirin.git@7cdc2e02ab7ef0b3f80aaa88f930ff34015d240a",
  "rich==15.0.0",
]

[tool.uv]
required-version = ">=0.12,<0.13"
override-dependencies = [
  "kirin-toolchain @ git+https://github.com/QuEraComputing/kirin.git@7cdc2e02ab7ef0b3f80aaa88f930ff34015d240a",
]
